Listening on 3000
{ name: 'Starbucks Corporation',
  location: '655 Grand Blvd  Destin Florida, 32550-1841 United States',
  twitter: 'https://twitter.com/starbucks',
  linkedin: 'https://www.linkedin.com/company/starbucks',
  facebook: 'https://www.facebook.com/starbucks',
  bio:
   'Starbucks Corporation is an American coffee company and coffeehouse chain.',  logo:
   'https://img.fullcontact.com/static/7b3d6cdd953d34cda63076ff5fc6e969_a0d3476abb4da924fd2d30a28307d64d724fc621abc6cefaea0068bf12d94f0f',
  website: 'http://www.starbucks.com',
  founded: 1971,
  employees: 104128,
  locale: 'en',
  category: 'Other',
  details:
   { locales: [ [Object] ],
     categories: [ [Object] ],
     industries: [ [Object], [Object] ],
     emails: [],
     phones: [ [Object] ],
     profiles:
      { angellist: [Object],
        youtube: [Object],
        twitter: [Object],
        crunchbasecompany: [Object],
        linkedincompany: [Object],
        facebook: [Object],
        pinterest: [Object],
        google: [Object],
        instagram: [Object] },
     locations: [ [Object], [Object], [Object] ],
     images: [ [Object], [Object], [Object], [Object] ],
     urls:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     keywords:
      [ 'Brewed Coffee',
        'Caffe',
        'Card',
        'Coffee',
        'Cold Brew Coffee',
        'Consumer Goods',
        'Drinks',
        'Drip Coffee',
        'Espreso',
        'Espresso',
        'Expresso',
        'Find A Store',
        'Food',
        'Healthy Breakfast Options',
        'Home',
        'Hospitality',
        'Iced Coffee',
        'Instant Coffee',
        'Latte',
        'Loyalty Program',
        'Macchiato',
        'Menu',
        'Mocha',
        'Pike Place',
        'Responsibility',
        'Restaurant Chains',
        'Retail',
        'Rewards',
        'SBC',
        'SBUX',
        'Seattle',
        'Seattle’s Best',
        'Shop',
        'Sign up',
        'Starbuck',
        'Starbucks',
        'Starbucks.com',
        'Store Locator',
        'Via',
        'Whole Bean' ],
     keyPeople: [],
     traffic: { countryRank: [Object], localeRank: [Object] } },
  dataAddOns:
   [ { id: 'keypeople',
       name: 'Key People',
       enabled: false,
       applied: false,
       description:
        'Displays information about people of interest at this company.',
       docLink: 'http://docs.fullcontact.com/api/#key-people' } ],
  updated: '2018-12-01' }